//------------------------------------------------------------------------------
// <Auto-generated>
//     This code is generated by a tool.
//
//     Changes to this file may cause incorrect behavior, and if
//     the code is regenerated, these changes will be lost.
// </Auto-generated>
//------------------------------------------------------------------------------

namespace BlueWhale.UI.baseSet {
    
    
    public partial class AccountList {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Automatically generated field.
        /// To modify, move the field declaration from the designer file to the code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
