USE [BlueWhale_ERP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[clientType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[shopId] [int] NULL,
	[names] [varchar](100) NULL,
	[dis] [decimal](18, 2) NULL,
	[flag] [int] NULL,
	CONSTRAINT [PK__clientType__08EA5793] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	) 
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
	) 
	ON [PRIMARY]
) 
ON [PRIMARY]
GO