USE [BlueWhale_ERP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[dept](
	[deptId] [int] IDENTITY(1,1) NOT NULL,
	[deptName] [varchar](30) NULL,
	[ParentId] [int] NULL,
	[flag] [int] NULL,
 CONSTRAINT [PK_dept] PRIMARY KEY NONCLUSTERED 
(
	[deptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[dept] ADD  CONSTRAINT [DF_dept_flag]  DEFAULT ((0)) FOR [flag]
GO


