SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[goodsType](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[shopId] [int] NULL,
	[names] [varchar](100) NULL,
	[parentId] [int] NULL,
	[seq] [int] NULL,
 CONSTRAINT [PK__goodsType__0CBAE877] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO