USE [BlueWhale_ERP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Create Logs Table
CREATE TABLE [dbo].[logs] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [events] VARCHAR(5000) NULL,
    [users] VARCHAR(1000) NULL,
    [ip] VARCHAR(500) NULL,
    [date] DATETIME NULL CONSTRAINT [DF_logs_date] DEFAULT (GETDATE()),
    [shopId] INT NULL
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[logs] ADD  CONSTRAINT [PK_logs] PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
