USE [BlueWhale_ERP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[processList](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[shopId] [int] NULL,
	[typeId] [int] NULL,
	[names] [varchar](1000) NULL,
	[price] [float] NULL,
	[unitId] [int] NULL,
	[seq] [int] NULL,
 CONSTRAINT [PK__processList__102C51FF] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
